#!/usr/bin/env bash
# ============================================
# TradingBot23 — Quick Setup
# Paste your API keys and start paper trading
# ============================================

set -e

echo ""
echo "====================================="
echo "  TradingBot23 — Quick Setup"
echo "====================================="
echo ""

# Check if .env already exists
if [ -f .env ]; then
    read -rp ".env already exists. Overwrite? (y/N): " overwrite
    if [[ ! "$overwrite" =~ ^[Yy]$ ]]; then
        echo "Keeping existing .env. Done."
        exit 0
    fi
fi

echo "You need Binance API keys (read-only is enough for paper mode):"
echo ""
echo "  Binance API key — https://www.binance.com/en/my/settings/api-management"
echo "  Create a key with 'Read Only' — no trading permission needed for paper mode"
echo ""
echo "-------------------------------------"
echo ""

read -rp "Paste your BINANCE API KEY: " binance_key
read -rp "Paste your BINANCE API SECRET: " binance_secret

echo ""
echo ""
read -rp "Starting capital in USD [10000]: " capital
capital=${capital:-10000}

# Write .env
cat > .env << ENVEOF
# TradingBot23 Configuration — generated by setup.sh
BINANCE_API_KEY=${binance_key}
BINANCE_API_SECRET=${binance_secret}

TRADING_MODE=paper
ENGINE=futures
CAPITAL_USD=${capital}

# Strategy (defaults are good — edit later if you want)
MAX_HOLD_DAYS=3
DIP_THRESHOLD_PCT=0.02
PER_TRADE_PCT=0.20
CHECK_INTERVAL_HOURS=1
MONTHLY_CONTRIBUTION_USD=0
MONTHLY_CONTRIBUTION_DAY=1

# Futures settings
LEVERAGE=1
FUTURES_NET_TP_PCT=0.01
FUTURES_NET_SL_PCT=0.015
FUTURES_DIP_THRESHOLD_PCT=0.005
FUTURES_USE_SL=false

LOG_LEVEL=INFO
ENVEOF

echo ""
echo "====================================="
echo "  .env created! You're ready."
echo "====================================="
echo ""
echo "To start paper trading:"
echo ""
echo "  Option A — Run directly:"
echo "    pip install -r requirements.txt"
echo "    python -m bot.main --mode paper"
echo ""
echo "  Option B — Run with Docker:"
echo "    docker compose up -d"
echo "    docker compose logs -f"
echo ""
echo "  Futures paper bot: python -m bot.main --mode paper"
echo ""
