#!/usr/bin/env bash
# ============================================
# TradingBot23 — Quick Setup
# Paste your API keys and start paper trading
# ============================================

set -e

echo ""
echo "====================================="
echo "  TradingBot23 — Quick Setup"
echo "====================================="
echo ""

# Check if .env already exists
if [ -f .env ]; then
    read -rp ".env already exists. Overwrite? (y/N): " overwrite
    if [[ ! "$overwrite" =~ ^[Yy]$ ]]; then
        echo "Keeping existing .env. Done."
        exit 0
    fi
fi

echo "You need 2 API keys (both are FREE):"
echo ""
echo "  1. Binance API key    — https://www.binance.com/en/my/settings/api-management"
echo "     (Create a key with 'Read Only' — no trading permission needed for paper mode)"
echo ""
echo "  2. CoinMarketCap key  — https://pro.coinmarketcap.com/signup"
echo "     (Free tier gives 10,000 calls/month — more than enough)"
echo ""
echo "-------------------------------------"
echo ""

read -rp "Paste your BINANCE API KEY: " binance_key
read -rp "Paste your BINANCE API SECRET: " binance_secret
read -rp "Paste your COINMARKETCAP API KEY: " cmc_key

echo ""
echo "-------------------------------------"
echo "Choose engine:"
echo "  1) Spot (default — no leverage, simpler)"
echo "  2) Futures (paper-only, 2x leverage)"
read -rp "Engine [1]: " engine_choice

if [[ "$engine_choice" == "2" ]]; then
    engine="futures"
else
    engine="spot"
fi

echo ""
read -rp "Starting capital in USD [10000]: " capital
capital=${capital:-10000}

# Write .env
cat > .env << ENVEOF
# TradingBot23 Configuration — generated by setup.sh
BINANCE_API_KEY=${binance_key}
BINANCE_API_SECRET=${binance_secret}
CMC_API_KEY=${cmc_key}

TRADING_MODE=paper
ENGINE=${engine}
CAPITAL_USD=${capital}

# Strategy (defaults are good — edit later if you want)
NET_TP_PCT=0.01
NET_SL_PCT=0.015
FEE_PCT=0.001
MAX_HOLD_DAYS=3
DIP_THRESHOLD_PCT=0.02
PER_TRADE_PCT=0.20
CHECK_INTERVAL_HOURS=1

# Futures settings (only applies if ENGINE=futures)
LEVERAGE=2
FUTURES_NET_TP_PCT=0.005
FUTURES_NET_SL_PCT=0.0075
FUTURES_DIP_THRESHOLD_PCT=0.005

LOG_LEVEL=INFO
ENVEOF

echo ""
echo "====================================="
echo "  .env created! You're ready."
echo "====================================="
echo ""
echo "To start paper trading:"
echo ""
echo "  Option A — Run directly:"
echo "    pip install -r requirements.txt"
echo "    python -m bot.main --mode paper"
echo ""
echo "  Option B — Run with Docker:"
echo "    docker compose up -d"
echo "    docker compose logs -f"
echo ""
echo "  Spot:    python -m bot.main --mode paper --engine spot"
echo "  Futures: python -m bot.main --mode paper --engine futures"
echo ""
