"""First-run setup wizard with a simple GUI.

When no .env file is found (e.g. friend just double-clicked the .exe),
this wizard pops up asking for API keys and basic settings, then writes
a .env file so the bot can start.

Falls back to terminal prompts if no display is available (headless server).
"""

import os
import sys
from pathlib import Path


def _get_env_path() -> Path:
    if getattr(sys, "frozen", False):
        return Path(sys.executable).parent / ".env"
    from bot import config
    return config.PROJECT_ROOT / ".env"


def _needs_setup() -> bool:
    env_path = _get_env_path()
    if not env_path.exists():
        return True
    text = env_path.read_text()
    return "your_binance_api_key_here" in text or "BINANCE_API_KEY=" not in text


def _write_env(data: dict):
    env_path = _get_env_path()
    content = f"""# TradingBot23 - auto-generated by setup wizard
BINANCE_API_KEY={data['binance_key']}
BINANCE_API_SECRET={data['binance_secret']}

TRADING_MODE=paper
ENGINE={data['engine']}
CAPITAL_USD={data['capital']}

NET_TP_PCT=0.01
NET_SL_PCT=0.015
FEE_PCT=0.001
MAX_HOLD_DAYS=3
DIP_THRESHOLD_PCT=0.02
PER_TRADE_PCT=0.20
CHECK_INTERVAL_HOURS=1

LEVERAGE=2
FUTURES_NET_TP_PCT=0.005
FUTURES_NET_SL_PCT=0.0075
FUTURES_DIP_THRESHOLD_PCT=0.005

LOG_LEVEL=INFO
"""
    env_path.write_text(content, encoding="utf-8")


def run_gui_wizard() -> bool:
    """Show a tkinter setup wizard. Returns True if setup was completed."""
    try:
        import tkinter as tk
        from tkinter import ttk, messagebox
    except ImportError:
        return False

    completed = [False]

    root = tk.Tk()
    root.title("TradingBot23 — FutolTech Setup")
    root.geometry("520x480")
    root.resizable(False, False)

    try:
        root.configure(bg="#1a1a2e")
    except Exception:
        pass

    style = ttk.Style()
    style.theme_use("clam")

    frame = ttk.Frame(root, padding=20)
    frame.pack(fill="both", expand=True)

    ttk.Label(frame, text="TradingBot23 Setup", font=("Helvetica", 16, "bold")).pack(pady=(0, 2))
    ttk.Label(frame, text="Futol Ethical Technology Ecosystems", font=("Helvetica", 9, "italic")).pack(pady=(0, 10))
    ttk.Label(frame, text="Paste your API keys to start paper trading.").pack(pady=(0, 15))

    fields = {}

    def add_field(label_text, key, show=None):
        row = ttk.Frame(frame)
        row.pack(fill="x", pady=3)
        ttk.Label(row, text=label_text, width=22, anchor="w").pack(side="left")
        entry = ttk.Entry(row, width=40, show=show)
        entry.pack(side="left", fill="x", expand=True)
        fields[key] = entry

    add_field("Binance API Key:", "binance_key")
    add_field("Binance API Secret:", "binance_secret", show="*")

    sep = ttk.Separator(frame, orient="horizontal")
    sep.pack(fill="x", pady=10)

    engine_frame = ttk.Frame(frame)
    engine_frame.pack(fill="x", pady=3)
    ttk.Label(engine_frame, text="Engine:", width=22, anchor="w").pack(side="left")
    engine_var = tk.StringVar(value="spot")
    ttk.Radiobutton(engine_frame, text="Spot (simple)", variable=engine_var, value="spot").pack(side="left")
    ttk.Radiobutton(engine_frame, text="Futures (2x leverage)", variable=engine_var, value="futures").pack(side="left", padx=(10, 0))

    cap_frame = ttk.Frame(frame)
    cap_frame.pack(fill="x", pady=3)
    ttk.Label(cap_frame, text="Paper capital (USD):", width=22, anchor="w").pack(side="left")
    cap_entry = ttk.Entry(cap_frame, width=15)
    cap_entry.insert(0, "10000")
    cap_entry.pack(side="left")

    ttk.Label(frame, text="").pack()

    info_text = (
        "Get your Binance API keys:\n"
        "  binance.com > Profile > API Management\n"
        "  Enable: Read Info + Spot Trading (for live mode)"
    )
    info_label = ttk.Label(frame, text=info_text, font=("Courier", 9), justify="left")
    info_label.pack(pady=(5, 10))

    def on_save():
        data = {
            "binance_key": fields["binance_key"].get().strip(),
            "binance_secret": fields["binance_secret"].get().strip(),
            "engine": engine_var.get(),
            "capital": cap_entry.get().strip() or "10000",
        }

        missing = []
        if not data["binance_key"]:
            missing.append("Binance API Key")
        if not data["binance_secret"]:
            missing.append("Binance API Secret")

        if missing:
            messagebox.showwarning("Missing Keys", "Please fill in:\n" + "\n".join(f"  - {m}" for m in missing))
            return

        _write_env(data)
        completed[0] = True
        messagebox.showinfo("Ready!", "Config saved! The bot will now start paper trading.")
        root.destroy()

    btn_frame = ttk.Frame(frame)
    btn_frame.pack(pady=10)
    ttk.Button(btn_frame, text="Save & Start Bot", command=on_save).pack(side="left", padx=5)
    ttk.Button(btn_frame, text="Quit", command=root.destroy).pack(side="left", padx=5)

    root.mainloop()
    return completed[0]


def run_terminal_wizard() -> bool:
    """Fallback: terminal-based setup for headless servers."""
    print("\n===== TradingBot23 — First-Time Setup =====\n")
    print("You need your Binance API keys:")
    print("  binance.com > Profile > API Management\n")

    binance_key = input("Paste Binance API KEY: ").strip()
    binance_secret = input("Paste Binance API SECRET: ").strip()

    if not all([binance_key, binance_secret]):
        print("Error: Both Binance keys are required.")
        return False

    engine_choice = input("Engine — 1) Spot  2) Futures [1]: ").strip()
    engine = "futures" if engine_choice == "2" else "spot"
    capital = input("Paper capital USD [10000]: ").strip() or "10000"

    _write_env({
        "binance_key": binance_key,
        "binance_secret": binance_secret,
        "engine": engine,
        "capital": capital,
    })

    print("\nConfig saved! Starting bot...\n")
    return True


def ensure_setup() -> bool:
    """Run the setup wizard if needed. Returns True if bot can proceed."""
    if not _needs_setup():
        return True

    if run_gui_wizard():
        return True

    return run_terminal_wizard()
